name: Podman CI

on:
  push:
    branches: [ "main" ]

jobs:

  git-pull:
    runs-on: self-hosted
    steps:
    - name: pull
      run: git pull
  build:
    needs: git-pull
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build Rooms Web
      run: make build-prod
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Deploy/Restart Rooms Web
      run: |
        make kill-prod |
        make run-prod
